# MySQL. Versions 5.7 and up are supported.
#
# Install the mysql2 gem:
#   gem install mysql2
#
# Ensure MySQL is installed and running, then create databases:
#   rails db:create db:migrate db:seed
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "root" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>
  port: <%= ENV.fetch("DB_PORT") { 3306 } %>

development:
  <<: *default
  database: acciobnb_development

test:
  <<: *default
  database: acciobnb_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
